import type { Metadata } from "next";
import { Layout } from "nextra-theme-docs";
import 'nextra-theme-docs/style.css';
import { Head, Search } from "nextra/components";
import { getPageMap } from "nextra/page-map";
import "./globals.css";
import { Inter, JetBrains_Mono } from "next/font/google";
import { cn } from "@/lib/utils";

const jetbrainsMonoHeading = JetBrains_Mono({subsets:['latin'],variable:'--font-heading'});

const inter = Inter({subsets:['latin'],variable:'--font-sans'});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pageMap = getPageMap()

  return (
    <html lang="en" suppressHydrationWarning className={cn("font-sans", inter.variable, jetbrainsMonoHeading.variable)}>
      <Head />

      <body>
        <Layout
          search={<Search />}
          pageMap={await pageMap}
          >
          {children}
        </Layout>
      </body>
    </html>
  );
}
