name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:

env:
  BUN_VERSION: 1.2.15

jobs:
  test:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Setup Bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: ${{ env.BUN_VERSION }}
    
    - name: Get Bun cache directory
      id: bun-cache
      run: echo "dir=$(bun pm cache)" >> $GITHUB_OUTPUT
      shell: bash
    
    - name: Cache Bun dependencies
      uses: actions/cache@v4
      with:
        path: ${{ steps.bun-cache.outputs.dir }}
        key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lockb') }}
        restore-keys: |
          ${{ runner.os }}-bun-
    
    - name: Install dependencies
      run: bun install --frozen-lockfile
    
    - name: Run linter
      run: bun run lint || true
      continue-on-error: true
    
    - name: Run tests
      run: bun test
    
    - name: Run tests with coverage
      run: bun test --coverage || true
      continue-on-error: true
    
    - name: Build project
      run: bun run build || echo "No build script found"
    
    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results-${{ matrix.os }}
        path: |
          coverage/
          test-results/
        retention-days: 7 